### model
model_name_or_path: "/home/lgd/common/ComfyUI/models/LLM/qwen/Qwen2-VL-7B-Instruct/"

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all
deepspeed: "/home/lgd/e_commerce_lmm/LLaMA-Factory-0.9.0/examples/deepspeed/ds_z2_config.json"


### dataset
dataset_dir: /home/lgd/e_commerce_lmm/LLaMA-Factory-0.9.0/data/
dataset: xray  # video: mllm_video_demo
template: qwen2_vl
cutoff_len: 1024
#max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: /home/lgd/e_commerce_lmm/LLaMA-Factory-0.9.0/saves/qwen2_vl-7b/lora/sft
logging_steps: 10
save_steps: 1000
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 8
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.1
per_device_eval_batch_size: 8
eval_strategy: steps
eval_steps: 1000
